AllCops:
  Exclude:
    - 'jpostcode.gemspec'
    - 'jpostcode-data/**/*'
    - 'vendor/bundle/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/MutableConstant:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 30
