version: 2

jobs:
  ruby-2.6:
    docker:
      - image: ruby:2.6.5
    steps:
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
            gem install bundler
            bundle install
            bundle exec rake
            bundle exec rubocop

workflows:
  version: 2
  test:
    jobs:
      - ruby-2.6
