version: 2.1

jobs:
  ruby:
    docker:
      - image: rubylang/ruby:2.6.5-bionic
    steps:
      - run:
          name: Install System Dependencies
          # https://circleci.com/docs/2.0/custom-images/#required-tools-for-primary-containers
          command: apt-get update -y && apt-get install -y ssh
      - checkout
      - run:
          name: submodule update and execute
          command: |
            git submodule init
            git submodule update
            gem install bundler
            bundle install
            bundle exec rake
            bundle exec rubocop

workflows:
  version: 2
  test:
    jobs:
      - ruby
